In [106]:
import numpy as np
import pandas as pd

In [107]:
#Creating DataFrame
#DataFrame is always created using a dictionary
d = {
    'Name': ['Ram', 'Sita', 'Gita', 'Hari', 'Shyam'],
    'Roll': [111, 222, 333, 444, 555],
    'Course': ['AIML', 'Python', 'AIML', 'C', 'JAVA']
    }
d

{'Name': ['Ram', 'Sita', 'Gita', 'Hari', 'Shyam'],
 'Roll': [111, 222, 333, 444, 555],
 'Course': ['AIML', 'Python', 'AIML', 'C', 'JAVA']}

In [108]:
df = pd.DataFrame(d)

In [109]:
df

    Name  Roll  Course
0    Ram   111    AIML
1   Sita   222  Python
2   Gita   333    AIML
3   Hari   444       C
4  Shyam   555    JAVA

In [110]:
df[2]

KeyError: 2

In [111]:
#indexing
df.Name[2]

'Gita'

In [112]:
df.Course[0]

'AIML'

In [113]:
#slicing
#iloc - used for slicing on DataFrame
#Syntax - df.iloc[row_index, col_index]
df.iloc[::, ::]

    Name  Roll  Course
0    Ram   111    AIML
1   Sita   222  Python
2   Gita   333    AIML
3   Hari   444       C
4  Shyam   555    JAVA

In [114]:
df.iloc[1, ::]

Name        Sita
Roll         222
Course    Python
Name: 1, dtype: object

In [115]:
df.iloc[::, 2]

0      AIML
1    Python
2      AIML
3         C
4      JAVA
Name: Course, dtype: object

In [116]:
df.iloc[::2, ::]

    Name  Roll Course
0    Ram   111   AIML
2   Gita   333   AIML
4  Shyam   555   JAVA

In [117]:
df.iloc[1::2, ::]

   Name  Roll  Course
1  Sita   222  Python
3  Hari   444       C

In [118]:
df.iloc[1::2, ::2]

   Name  Course
1  Sita  Python
3  Hari       C

In [119]:
# head - it represent the top rows head() - bydefault 5 rows
df.head(3)

   Name  Roll  Course
0   Ram   111    AIML
1  Sita   222  Python
2  Gita   333    AIML

In [120]:
# tail - it represent bottom rows
df.tail(3)

    Name  Roll Course
2   Gita   333   AIML
3   Hari   444      C
4  Shyam   555   JAVA

In [121]:
# sample() - it returns random sample from the rows
df.sample()

   Name  Roll  Course
1  Sita   222  Python

In [122]:
df.sample(3)

   Name  Roll  Course
0   Ram   111    AIML
3  Hari   444       C
1  Sita   222  Python

In [127]:
df = df.rename(columns={'Name': 'Student_Name'})
df

  Student_Name  Roll  Course
0          Ram   111    AIML
1         Sita   222  Python
2         Gita   333    AIML
3         Hari   444       C
4        Shyam   555    JAVA

In [128]:
df.set_index('Roll')

     Student_Name  Course
Roll
111           Ram    AIML
222          Sita  Python
333          Gita    AIML
444          Hari       C
555         Shyam    JAVA

In [129]:
# set_index - csn set any col as index position
# df = df.set_index('Roll')
# df.set_index('Roll', inplace=True)
df.set_index('Roll', inplace=True)

In [130]:
df

     Student_Name  Course
Roll
111           Ram    AIML
222          Sita  Python
333          Gita    AIML
444          Hari       C
555         Shyam    JAVA

In [104]:
df = df.reset_index()

In [131]:
df

     Student_Name  Course
Roll
111           Ram    AIML
222          Sita  Python
333          Gita    AIML
444          Hari       C
555         Shyam    JAVA

In [132]:
df.Course[333]

'AIML'

In [ ]:
df = pd.DataFrame({
    'Days': [1,2,3,4,5],
    'Places': ['Puri', 'Mathura', 'Asansol', 'Manali', 'Kolkata'],
    'Visitors': [5895, 5600, 48]
})