In [1]:
import numpy as np
import pandas as pd

In [2]:
#Creating DataFrame
#DataFrame is always created using a dictionary
d = {
    'Name': ['Ram', 'Sita', 'Gita', 'Hari', 'Shyam'],
    'Roll': [111, 222, 333, 444, 555],
    'Course': ['AIML', 'Python', 'AIML', 'C', 'JAVA']
    }
d

{'Name': ['Ram', 'Sita', 'Gita', 'Hari', 'Shyam'],
 'Roll': [111, 222, 333, 444, 555],
 'Course': ['AIML', 'Python', 'AIML', 'C', 'JAVA']}

In [3]:
df = pd.DataFrame(d)

In [4]:
df

    Name  Roll  Course
0    Ram   111    AIML
1   Sita   222  Python
2   Gita   333    AIML
3   Hari   444       C
4  Shyam   555    JAVA

In [5]:
df[2]

KeyError: 2

In [7]:
#indexing
df.Name[2]

'Gita'

In [8]:
df.Course[0]

'AIML'

In [14]:
#slicing
#iloc - used for slicing on DataFrame
#Syntax - df.iloc[row_index, col_index]
df.iloc[::, ::]

    Name  Roll  Course
0    Ram   111    AIML
1   Sita   222  Python
2   Gita   333    AIML
3   Hari   444       C
4  Shyam   555    JAVA

In [15]:
df.iloc[1, ::]

Name        Sita
Roll         222
Course    Python
Name: 1, dtype: object

In [16]:
df.iloc[::, 2]

0      AIML
1    Python
2      AIML
3         C
4      JAVA
Name: Course, dtype: object

In [17]:
df.iloc[::2, ::]

    Name  Roll Course
0    Ram   111   AIML
2   Gita   333   AIML
4  Shyam   555   JAVA

In [18]:
df.iloc[1::2, ::]

   Name  Roll  Course
1  Sita   222  Python
3  Hari   444       C