In [1]:
import numpy as np
import pandas as pd

In [2]:
iris = pd.read_csv('iris.data')
iris

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]

In [3]:
iris = pd.read_csv('iris.data', header=None)
iris

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [5]:
iris.columns = ['SL', 'SW', 'PL', 'PW', 'Flower Type']
iris

      SL   SW   PL   PW     Flower Type
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [6]:
iris.head()

    SL   SW   PL   PW  Flower Type
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [7]:
iris.head(10)

    SL   SW   PL   PW  Flower Type
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa
5  5.4  3.9  1.7  0.4  Iris-setosa
6  4.6  3.4  1.4  0.3  Iris-setosa
7  5.0  3.4  1.5  0.2  Iris-setosa
8  4.4  2.9  1.4  0.2  Iris-setosa
9  4.9  3.1  1.5  0.1  Iris-setosa

In [8]:
iris.tail(7)

      SL   SW   PL   PW     Flower Type
143  6.8  3.2  5.9  2.3  Iris-virginica
144  6.7  3.3  5.7  2.5  Iris-virginica
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

In [9]:
iris.isnull()

        SL     SW     PL     PW  Flower Type
0    False  False  False  False        False
1    False  False  False  False        False
2    False  False  False  False        False
3    False  False  False  False        False
4    False  False  False  False        False
..     ...    ...    ...    ...          ...
145  False  False  False  False        False
146  False  False  False  False        False
147  False  False  False  False        False
148  False  False  False  False        False
149  False  False  False  False        False

[150 rows x 5 columns]

In [10]:
iris.isnull().sum()

SL             0
SW             0
PL             0
PW             0
Flower Type    0
dtype: int64

In [11]:
iris.dtypes

SL             float64
SW             float64
PL             float64
PW             float64
Flower Type     object
dtype: object

In [12]:
iris.SL.dtypes

dtype('float64')

In [13]:
iris['Flower Type'].dtypes

dtype('O')

In [14]:
iris['SL'].dtypes

dtype('float64')

In [15]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   SL           150 non-null    float64
 1   SW           150 non-null    float64
 2   PL           150 non-null    float64
 3   PW           150 non-null    float64
 4   Flower Type  150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [16]:
iris.SL.unique()

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.4, 4.8, 4.3, 5.8, 5.7, 5.2, 5.5,
       4.5, 5.3, 7. , 6.4, 6.9, 6.5, 6.3, 6.6, 5.9, 6. , 6.1, 5.6, 6.7,
       6.2, 6.8, 7.1, 7.6, 7.3, 7.2, 7.7, 7.4, 7.9])

In [17]:
iris['Flower Type'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [18]:
iris.columns

Index(['SL', 'SW', 'PL', 'PW', 'Flower Type'], dtype='object')

In [19]:
for i in iris.columns:
    print(iris[i].unique())

[5.1 4.9 4.7 4.6 5.  5.4 4.4 4.8 4.3 5.8 5.7 5.2 5.5 4.5 5.3 7.  6.4 6.9
 6.5 6.3 6.6 5.9 6.  6.1 5.6 6.7 6.2 6.8 7.1 7.6 7.3 7.2 7.7 7.4 7.9]
[3.5 3.  3.2 3.1 3.6 3.9 3.4 2.9 3.7 4.  4.4 3.8 3.3 4.1 4.2 2.3 2.8 2.4
 2.7 2.  2.2 2.5 2.6]
[1.4 1.3 1.5 1.7 1.6 1.1 1.2 1.  1.9 4.7 4.5 4.9 4.  4.6 3.3 3.9 3.5 4.2
 3.6 4.4 4.1 4.8 4.3 5.  3.8 3.7 5.1 3.  6.  5.9 5.6 5.8 6.6 6.3 6.1 5.3
 5.5 6.7 6.9 5.7 6.4 5.4 5.2]
[0.2 0.4 0.3 0.1 0.5 0.6 1.4 1.5 1.3 1.6 1.  1.1 1.8 1.2 1.7 2.5 1.9 2.1
 2.2 2.  2.4 2.3]
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

In [20]:
for i in iris.columns:
    print(i, ':', '\n', iris[i].unique(), '\n')

SL :
 [5.1 4.9 4.7 4.6 5.  5.4 4.4 4.8 4.3 5.8 5.7 5.2 5.5 4.5 5.3 7.  6.4 6.9
 6.5 6.3 6.6 5.9 6.  6.1 5.6 6.7 6.2 6.8 7.1 7.6 7.3 7.2 7.7 7.4 7.9]

SW :
 [3.5 3.  3.2 3.1 3.6 3.9 3.4 2.9 3.7 4.  4.4 3.8 3.3 4.1 4.2 2.3 2.8 2.4
 2.7 2.  2.2 2.5 2.6]

PL :
 [1.4 1.3 1.5 1.7 1.6 1.1 1.2 1.  1.9 4.7 4.5 4.9 4.  4.6 3.3 3.9 3.5 4.2
 3.6 4.4 4.1 4.8 4.3 5.  3.8 3.7 5.1 3.  6.  5.9 5.6 5.8 6.6 6.3 6.1 5.3
 5.5 6.7 6.9 5.7 6.4 5.4 5.2]

PW :
 [0.2 0.4 0.3 0.1 0.5 0.6 1.4 1.5 1.3 1.6 1.  1.1 1.8 1.2 1.7 2.5 1.9 2.1
 2.2 2.  2.4 2.3]

Flower Type :
 ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

In [21]:
iris.describe()

               SL          SW          PL          PW
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667
std      0.828066    0.433594    1.764420    0.763161
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [22]:
iris.describe(include='all')

                SL          SW          PL          PW  Flower Type
count   150.000000  150.000000  150.000000  150.000000          150
unique         NaN         NaN         NaN         NaN            3
top            NaN         NaN         NaN         NaN  Iris-setosa
freq           NaN         NaN         NaN         NaN           50
mean      5.843333    3.054000    3.758667    1.198667          NaN
std       0.828066    0.433594    1.764420    0.763161          NaN
min       4.300000    2.000000    1.000000    0.100000          NaN
25%       5.100000    2.800000    1.600000    0.300000          NaN
50%       5.800000    3.000000    4.350000    1.300000          NaN
75%       6.400000    3.300000    5.100000    1.800000          NaN
max       7.900000    4.400000    6.900000    2.500000          NaN

In [23]:
iris.SL.value_counts()

SL
5.0    10
5.1     9
6.3     9
5.7     8
6.7     8
5.8     7
5.5     7
6.4     7
4.9     6
5.4     6
6.1     6
6.0     6
5.6     6
4.8     5
6.5     5
6.2     4
7.7     4
6.9     4
4.6     4
5.2     4
5.9     3
4.4     3
7.2     3
6.8     3
6.6     2
4.7     2
7.6     1
7.4     1
7.3     1
7.0     1
7.1     1
5.3     1
4.3     1
4.5     1
7.9     1
Name: count, dtype: int64

In [24]:
iris.drop('SL')

KeyError: "['SL'] not found in axis"

In [25]:
iris.drop('SL', axis=1)

      SW   PL   PW     Flower Type
0    3.5  1.4  0.2     Iris-setosa
1    3.0  1.4  0.2     Iris-setosa
2    3.2  1.3  0.2     Iris-setosa
3    3.1  1.5  0.2     Iris-setosa
4    3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...             ...
145  3.0  5.2  2.3  Iris-virginica
146  2.5  5.0  1.9  Iris-virginica
147  3.0  5.2  2.0  Iris-virginica
148  3.4  5.4  2.3  Iris-virginica
149  3.0  5.1  1.8  Iris-virginica

[150 rows x 4 columns]

In [26]:
iris

      SL   SW   PL   PW     Flower Type
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [27]:
iris.drop('SL', axis=1, inplace=True)

In [28]:
iris

      SW   PL   PW     Flower Type
0    3.5  1.4  0.2     Iris-setosa
1    3.0  1.4  0.2     Iris-setosa
2    3.2  1.3  0.2     Iris-setosa
3    3.1  1.5  0.2     Iris-setosa
4    3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...             ...
145  3.0  5.2  2.3  Iris-virginica
146  2.5  5.0  1.9  Iris-virginica
147  3.0  5.2  2.0  Iris-virginica
148  3.4  5.4  2.3  Iris-virginica
149  3.0  5.1  1.8  Iris-virginica

[150 rows x 4 columns]